[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

# Performance headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

# PWA Support
[[headers]]
  for = "/neon-runner.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Content-Type-Options = "nosniff"

# Social Media Automation Webhook
# Configure this URL in your Zapier/automation platform
[[plugins]]
  package = "@netlify/plugin-functions"

[plugins.inputs]
  node_bundler = "esbuild"

# SPA routing for PWA
[[redirects]]
  from = "/*"
  to = "/neon-runner.html"
  status = 200

# API redirects for social automation
[[redirects]]
  from = "/api/social-webhook"
  to = "/.netlify/functions/social-webhook"
  status = 200

# Gzip compression
[[headers]]
  for = "*.html"
  [headers.values]
    Content-Encoding = "gzip"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Encoding = "gzip"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Encoding = "gzip"

# Security headers for monetization
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.google.com *.googlesyndication.com *.googletagmanager.com *.gstatic.com data: blob:; img-src 'self' 'unsafe-inline' data: blob: *.google.com *.googlesyndication.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.google.com *.googlesyndication.com *.googletagmanager.com *.gstatic.com; style-src 'self' 'unsafe-inline' *.googleapis.com; font-src 'self' *.googleapis.com *.gstatic.com data:; connect-src 'self' *.google.com *.googlesyndication.com *.googletagmanager.com;"

# Environment specific settings
[context.production.environment]
  SOCIAL_AUTOMATION = "enabled"
  CROSS_PROMOTION = "enabled"
  ANALYTICS_DEBUG = "false"

[context.deploy-preview.environment]
  SOCIAL_AUTOMATION = "disabled"
  CROSS_PROMOTION = "enabled"
  ANALYTICS_DEBUG = "true"

